[package]
name = "conditional_token_price"
version = "0.1.0"
edition = "2021"

[dependencies]
solana-client = "1.18.19"
solana-sdk = "1.18.19"
tokio = { version = "1.0", features = ["full"] }
solana-account-decoder = "1.18.19"

[[bin]]
name = "conditional_token_price"
path = "src/main.rs"
